[build]
  base    = "mitchellBuilds"
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

  [plugins.inputs]
    excludedRoutes = []

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP_FORMS = "true"

[[headers]]
  for = "/*"
  [headers.values]
    Clear-Site-Data = '"cache", "cookies", "storage", "executionContexts"'

[[redirects]]
  from = "https://techwrench.co/*"
  to = "https://www.techwrench.co/:splat"
  status = 301
  force = true